%YAML:1.0
---
Markers:
  - Points:
      -
        freq: 10000
        x: -0.015
        y: 0.015
        z: 0.0
      -
        freq: 10000
        x: 0.015
        y: 0.015
        z: 0.0
      -
        freq: 10000
        x: 0.015
        y: -0.015
        z: 0.0
      -
        freq: 10000
        x: -0.015
        y: -0.015
        z: 0.0
    ID: 1